[project]
name = "fugashi-runner"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = "~=3.10.0"
dependencies = [
    "fugashi>=1.5.2",
    "unidic-lite>=1.0.8",
]
